## Create a logical gate using a  simple DNN

In [7]:
from keras import models
from keras import layers
from keras.layers import Dense, Dropout
import numpy as np


In [8]:
model = models.Sequential()
model.add(Dense(8, activation='relu', input_dim=2))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid')) # if y is 0 or 1
print(model.summary())
model.compile(optimizer='rmsprop', loss='mse', metrics=['accuracy'])


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 8)                 24        
_________________________________________________________________
dense_10 (Dense)             (None, 16)                144       
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 17        
Total params: 185
Trainable params: 185
Non-trainable params: 0
_________________________________________________________________
None


In [9]:
def logical_gate(X,Y): 
    model = models.Sequential()
    model.add(Dense(8, activation='relu', input_dim=2))
    model.add(Dense(16, activation='relu'))
    model.add(Dense(1, activation='sigmoid')) # if y is 0 or 1
    #print(model.summary())
    model.compile(optimizer='rmsprop', loss='mse', metrics=['accuracy'])
    model.fit(X, Y,epochs=200,verbose=0)
    return model


def gate_predict_prob(model,X):
    return model.predict(X)


def gate_predict(model,X):
    return np.round(model.predict(X))


In [10]:
X_train=np.array([[0., 0.],[0., 1.],[1., 0.],[1., 1.]])
Y_train=np.array([0,1,1,0]) 
xor_gate=logical_gate(X_train,Y_train)
gate_predict(xor_gate,X_train)


array([[0.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [11]:
xor_gate.predict(X_train)

array([[0.38054493],
       [0.87142086],
       [0.5555722 ],
       [0.23967096]], dtype=float32)

In [12]:
X_train=np.array([[0., 0.],[0., 1.],[1., 0.],[1., 1.]])
Y_train=np.array([0,0,0,1])
and_gate=logical_gate(X_train,Y_train)
gate_predict(and_gate,X_train)

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)