# Keras : 5個步驟建立DNN模型

In [ ]:
import tensorflow as tf
tf.__version__

In [2]:
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import RMSprop
from keras.utils import np_utils

from sklearn.model_selection import train_test_split

## Define Network

In [48]:
model = Sequential()
model.add(Dense(5, input_dim=2))
model.add(Activation('relu'))
model.add(Dense(1))
model.add(Activation('sigmoid'))
print(model.summary())
model.compile(optimizer='sgd', loss='mse', metrics=['accuracy'])


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 5)                 15        
_________________________________________________________________
activation_4 (Activation)    (None, 5)                 0         
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 6         
_________________________________________________________________
activation_5 (Activation)    (None, 1)                 0         
Total params: 21
Trainable params: 21
Non-trainable params: 0
_________________________________________________________________
None


## Prepare data

In [49]:
X = np.array([100,50,40,20,70,-50,-32,-50,-40,-10]).reshape(-1,2)
print(X.shape)
y = np.array([1,1,1,0,0])
print(y.shape)
print(X)
print(y)

(5, 2)
(5,)
[[100  50]
 [ 40  20]
 [ 70 -50]
 [-32 -50]
 [-40 -10]]
[1 1 1 0 0]


## training 

In [64]:
history=model.fit(X, y, batch_size=2, epochs=10)
#loss, accuracy = model.evaluate(X, y)


Epoch 1/10
3/3 [==============================] - 0s 2ms/step - loss: 4.8752e-11 - accuracy: 1.0000
Epoch 2/10
3/3 [==============================] - 0s 3ms/step - loss: 4.8752e-11 - accuracy: 1.0000
Epoch 3/10
3/3 [==============================] - 0s 2ms/step - loss: 4.8752e-11 - accuracy: 1.0000
Epoch 4/10
3/3 [==============================] - 0s 3ms/step - loss: 4.8752e-11 - accuracy: 1.0000
Epoch 5/10
3/3 [==============================] - 0s 3ms/step - loss: 4.8752e-11 - accuracy: 1.0000
Epoch 6/10
3/3 [==============================] - 0s 2ms/step - loss: 4.8752e-11 - accuracy: 1.0000
Epoch 7/10
3/3 [==============================] - 0s 2ms/step - loss: 4.8752e-11 - accuracy: 1.0000
Epoch 8/10
3/3 [==============================] - 0s 2ms/step - loss: 4.8752e-11 - accuracy: 1.0000
Epoch 9/10
3/3 [==============================] - 0s 3ms/step - loss: 4.8752e-11 - accuracy: 1.0000
Epoch 10/10
3/3 [==============================] - 0s 2ms/step - loss: 4.8752e-11 - accuracy: 1.0000

## model evaluation

In [70]:
loss, accuracy = model.evaluate(X, y)


1/1 [==============================] - 0s 2ms/step - loss: 4.8752e-11 - accuracy: 1.0000


## model prediction

In [71]:
probabilities = model.predict(X)
predictions = [int(np.round(x)) for x in probabilities]
predictions



[1, 1, 1, 0, 0]

In [72]:
probabilities

array([[1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.5455698e-05],
       [2.2091717e-06]], dtype=float32)

## model score

In [73]:
accuracy = np.mean(predictions == y)
accuracy

1.0